travis:
  secure:
    BINSTAR_TOKEN: jCfs3vLhV67UwfUeHkg0USJA4h/qbHDGuh61HIj5K/qi/zbMGpXm2RvSPBw4vnBl/ge/mZIWaJwihxZOshTt2XVG0KICXP2mBlC7sQYy0Gpi8rmxOT8MEwzIC+4e1MEx0G6j/RJhkftE1COL26U0BY3a64+BUCjPdsaL+hueM5GFVXUywhtAcy8CDGL7Kv+ZSgoIxjBRzT0XAX39gUG2CjL9W+5b3pdfKTcgiEqK4/2fA/8SaKm0JQDOtkP+83DKJOccURCtf1GreMK9LtseLJqvvshb0w/Ho8SypXovQjkCoTEtQ6EiFbVQogklYf0HIkcXxE270T7InGr68OE7kLxYBPDRgRLE1+WwLVp4IUQYUyLeii50gXmlZ3EfZp3JV2orD4vLI3gH8dEwKyT6WkIQRIeITxDS61TQc1HddeAKzRzdjqFvikWWvDUHKqRORC9wyHrDiKW/O9IrcjwJv2U51E12gh6IolgSiG7rEPjMgyzFQUj08yV7bC/7BzXT52CjtIp/ij65r+Wee65XcljioKkxXLfeZoIdDGp9vaicCtT2DTNLgaFqI7JMlINhgyg69NaJaIKV9o+ZqVppDsS9sNRH8JEV8W5mlm8sZoOUpyce4mhwqxKhLuVTZlnhisTfCABWtDYXH0z12GMjn8Lj7EgGm3c0HsDhtjAwp60=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
