travis:
  secure:
    BINSTAR_TOKEN: ABdMGB2DwNQm4WTwdCOKPpUS+E/UFsj7ljYtpQDvGTH1QF3Y+ileTT0CRVYJn75nMECy6R+kweaXO5e6QiksJzZPXAc/VyTOYIY7O+w3m4CTtwecJrFPnZ0u2cttjbz9NAUZ7po0icgk+5M18OJXc/I6wpIzU4PVJP8iZ8GWARmJkUWTpsolfl9Zal9m9e/bpJQ3gZfuCWPQuHHJSJKdjdG7x0VjEV5TSxogi8uOwjW/fgVtfqZ7q79+ppEmQ05tbW0ugICHDSh8xhh3pJdopR7k1Xtp5M8QUiMHUQhb6ZwcElu7O63tiTS+SGIB1/0fk2pcBDMQKPrf09BILp1jaaP9gTgD3H7SB0sNqwm34KEeGsN+9/A4jENiYyan7QxUkp6K6QwvOQim4lS4vrgRlABPcLaOEgq37MlGbF/XjtwaOnVTXPMt4nX/dq6lQb0j+uWDLgJCpSzBgKBzIPdSIUcNJjrPlSh/4d3o+uH/mvXujr+I5OSEvJRSKEH4YbKvXmBHs6fDR0JhltIhfgQKjgesnbOoYpkNQYj/aojMaiHPdV8AcSeC9yfBrC2HtF+vO+WKaAGSr5qpl3ggAshQ/UodfBGCP+MtQvQUV/Iuk1ilxoRGkjH5wQYgaTlYHIZ+c+6bv2NN3NbMWrH63Qk09Ju9AieBpo+gfYtyWtq5rxc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
